services:
  
  # The target API which the reverse proxy routes to, inside the cluster
  httpbin-service:
    image: kennethreitz/httpbin
    hostname: apiserver

  # Valgrind runs NGINX, which routes to the target API
  nginx-service:
    image: nginx_${DISTRO}:${NGINX_DEPLOY_VERSION}
    ports:
    - 8080:8080
    volumes:
    - ./nginx.conf:${CONF_PATH}
    - ../../build/${MODULE_FILE}:${MODULE_FOLDER}/ngx_curity_http_phantom_token_module.so
    command: >
      sh -c "/usr/bin/valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=/valgrind-results.txt /usr/sbin/nginx"

  # Called from the test.sh script to get tokens, and by the module to introspect tokens
  curity-service:
    image: curity.azurecr.io/curity/idsvr
    hostname: identityserver
    ports:
      - 6749:6749
      - 8443:8443
    environment:
      ADMIN: 'true'
      SERVICE_ROLE: 'default'
      LICENSE_KEY: ${LICENSE_KEY}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ../curity-test-config.xml:/opt/idsvr/etc/init/curity-test-config.xml
